/**
 * MOJAVOX Campaign Report Page
 * Style: Cyberpunk Corporate
 * 
 * Features:
 * - Detailed campaign performance analysis
 * - PDF report generation
 * - Charts and metrics visualization
 * - Export options
 */

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import {
  ArrowLeft,
  BarChart3,
  Calendar,
  CheckCircle,
  Clock,
  DollarSign,
  Download,
  FileText,
  Phone,
  Printer,
  Share2,
  Target,
  TrendingUp,
  Users,
  XCircle,
} from "lucide-react";
import { useState, useEffect } from "react";
import { toast } from "sonner";
import { Link, useParams } from "wouter";
import { PageTransition, StaggerContainer, StaggerItem, AnimatedCounter } from "@/components/ui/page-transition";

// Mock campaign data
const campaignData = {
  id: "camp_1",
  name: "Q1 2026 - High Value Recovery",
  status: "active",
  startDate: "2026-01-14",
  endDate: "2026-03-30",
  target: 5000000,
  recovered: 2450000,
  debtors: {
    total: 1250,
    contacted: 890,
    resolved: 456,
    pending: 394,
    unreachable: 200,
  },
  calls: {
    total: 4520,
    successful: 2890,
    voicemail: 980,
    noAnswer: 650,
    avgDuration: "4:32",
  },
  agents: [
    { id: "NOVA-01", name: "NOVA-01", calls: 1520, successRate: 72, recovered: 820000 },
    { id: "APEX-02", name: "APEX-02", calls: 1450, successRate: 68, recovered: 780000 },
    { id: "PULSE-04", name: "PULSE-04", calls: 1550, successRate: 65, recovered: 850000 },
  ],
  dailyProgress: [
    { date: "Jan 14", recovered: 120000, calls: 280 },
    { date: "Jan 15", recovered: 145000, calls: 320 },
    { date: "Jan 16", recovered: 98000, calls: 290 },
    { date: "Jan 17", recovered: 167000, calls: 350 },
    { date: "Jan 18", recovered: 189000, calls: 380 },
    { date: "Jan 19", recovered: 156000, calls: 340 },
    { date: "Jan 20", recovered: 178000, calls: 360 },
  ],
  paymentMethods: [
    { method: "Full Payment", count: 156, amount: 1200000 },
    { method: "Payment Plan", count: 234, amount: 850000 },
    { method: "Partial Payment", count: 66, amount: 400000 },
  ],
};

export default function CampaignReport() {
  const [loading, setLoading] = useState(true);
  const [selectedCampaign, setSelectedCampaign] = useState("camp_1");
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 800);
    return () => clearTimeout(timer);
  }, []);

  const handleGeneratePDF = async () => {
    setGenerating(true);
    await new Promise(resolve => setTimeout(resolve, 2000));
    setGenerating(false);
    toast.success("Report generated", { description: "campaign_report_q1_2026.pdf" });
    
    // Simulate PDF download
    const content = generateReportContent();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "campaign_report_q1_2026.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateReportContent = () => {
    return `
MOJAVOX CAMPAIGN PERFORMANCE REPORT
====================================
Generated: ${new Date().toLocaleDateString()}

CAMPAIGN: ${campaignData.name}
Status: ${campaignData.status.toUpperCase()}
Period: ${campaignData.startDate} - ${campaignData.endDate}

EXECUTIVE SUMMARY
-----------------
Target Amount: $${(campaignData.target / 1000000).toFixed(2)}M
Recovered: $${(campaignData.recovered / 1000000).toFixed(2)}M
Recovery Rate: ${Math.round(campaignData.recovered / campaignData.target * 100)}%

DEBTOR STATISTICS
-----------------
Total Debtors: ${campaignData.debtors.total}
Contacted: ${campaignData.debtors.contacted} (${Math.round(campaignData.debtors.contacted / campaignData.debtors.total * 100)}%)
Resolved: ${campaignData.debtors.resolved} (${Math.round(campaignData.debtors.resolved / campaignData.debtors.total * 100)}%)
Pending: ${campaignData.debtors.pending}
Unreachable: ${campaignData.debtors.unreachable}

CALL STATISTICS
---------------
Total Calls: ${campaignData.calls.total}
Successful: ${campaignData.calls.successful}
Voicemail: ${campaignData.calls.voicemail}
No Answer: ${campaignData.calls.noAnswer}
Avg Duration: ${campaignData.calls.avgDuration}

AGENT PERFORMANCE
-----------------
${campaignData.agents.map(a => `${a.name}: ${a.calls} calls, ${a.successRate}% success, $${(a.recovered / 1000).toFixed(0)}K recovered`).join("\n")}

---
Report generated by MOJAVOX AI Collection Platform
© 2026 Mojatoon. All rights reserved.
    `.trim();
  };

  const handlePrint = () => {
    window.print();
    toast.success("Print dialog opened");
  };

  const handleShare = () => {
    toast.success("Share link copied", { description: "Report link copied to clipboard" });
  };

  const recoveryRate = Math.round(campaignData.recovered / campaignData.target * 100);
  const contactRate = Math.round(campaignData.debtors.contacted / campaignData.debtors.total * 100);
  const resolutionRate = Math.round(campaignData.debtors.resolved / campaignData.debtors.contacted * 100);
  const maxDaily = Math.max(...campaignData.dailyProgress.map(d => d.recovered));

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-10 w-64 bg-muted animate-pulse rounded" />
        <div className="grid grid-cols-4 gap-4">
          {[1, 2, 3, 4].map(i => (
            <Card key={i} className="bg-card border-border">
              <CardContent className="p-6">
                <div className="h-20 bg-muted animate-pulse rounded" />
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    );
  }

  return (
    <PageTransition>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link href="/campaigns">
              <Button variant="ghost" size="icon">
                <ArrowLeft className="w-5 h-5" />
              </Button>
            </Link>
            <div>
              <h1 className="text-2xl font-display font-bold text-foreground flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-neon-green to-neon-blue flex items-center justify-center">
                  <FileText className="w-6 h-6 text-background" />
                </div>
                Campaign Report
              </h1>
              <p className="text-muted-foreground mt-1">Detailed performance analysis and metrics</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <Select value={selectedCampaign} onValueChange={setSelectedCampaign}>
              <SelectTrigger className="w-64 bg-background border-border">
                <SelectValue placeholder="Select campaign" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="camp_1">Q1 2026 - High Value Recovery</SelectItem>
                <SelectItem value="camp_2">Payment Reminder - 30 Days</SelectItem>
                <SelectItem value="camp_3">Legacy Accounts - Final Notice</SelectItem>
              </SelectContent>
            </Select>
            <Button variant="outline" size="icon" onClick={handlePrint}>
              <Printer className="w-4 h-4" />
            </Button>
            <Button variant="outline" size="icon" onClick={handleShare}>
              <Share2 className="w-4 h-4" />
            </Button>
            <Button 
              className="bg-neon-green text-background hover:bg-neon-green/90"
              onClick={handleGeneratePDF}
              disabled={generating}
            >
              {generating ? (
                <>
                  <Clock className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </>
              )}
            </Button>
          </div>
        </div>

        {/* Campaign Info */}
        <Card className="bg-gradient-to-br from-slate-800/50 to-slate-900/50 border-border">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <div className="flex items-center gap-3">
                  <h2 className="text-xl font-semibold text-foreground">{campaignData.name}</h2>
                  <Badge className="bg-neon-green/20 text-neon-green border-neon-green/30">
                    {campaignData.status}
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground mt-1">
                  <Calendar className="w-4 h-4 inline mr-1" />
                  {campaignData.startDate} → {campaignData.endDate}
                </p>
              </div>
              <div className="text-right">
                <p className="text-sm text-muted-foreground">Recovery Progress</p>
                <p className="text-3xl font-display font-bold text-neon-green">{recoveryRate}%</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Key Metrics */}
        <StaggerContainer className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <StaggerItem>
            <Card className="bg-card border-border">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Target</p>
                    <p className="text-2xl font-display font-bold text-foreground mt-1">
                      $<AnimatedCounter value={campaignData.target / 1000} />K
                    </p>
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-purple-500/10 flex items-center justify-center">
                    <Target className="w-6 h-6 text-purple-400" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </StaggerItem>
          <StaggerItem>
            <Card className="bg-card border-border">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Recovered</p>
                    <p className="text-2xl font-display font-bold text-neon-green mt-1">
                      $<AnimatedCounter value={campaignData.recovered / 1000} />K
                    </p>
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-neon-green/10 flex items-center justify-center">
                    <DollarSign className="w-6 h-6 text-neon-green" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </StaggerItem>
          <StaggerItem>
            <Card className="bg-card border-border">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Total Calls</p>
                    <p className="text-2xl font-display font-bold text-foreground mt-1">
                      <AnimatedCounter value={campaignData.calls.total} />
                    </p>
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-neon-blue/10 flex items-center justify-center">
                    <Phone className="w-6 h-6 text-neon-blue" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </StaggerItem>
          <StaggerItem>
            <Card className="bg-card border-border">
              <CardContent className="p-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Debtors Resolved</p>
                    <p className="text-2xl font-display font-bold text-foreground mt-1">
                      <AnimatedCounter value={campaignData.debtors.resolved} />
                    </p>
                  </div>
                  <div className="w-12 h-12 rounded-xl bg-amber-500/10 flex items-center justify-center">
                    <CheckCircle className="w-6 h-6 text-amber-400" />
                  </div>
                </div>
              </CardContent>
            </Card>
          </StaggerItem>
        </StaggerContainer>

        {/* Charts Row */}
        <div className="grid lg:grid-cols-2 gap-6">
          {/* Daily Progress */}
          <Card className="bg-card border-border">
            <CardHeader>
              <CardTitle className="text-foreground flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-neon-green" />
                Daily Recovery Progress
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="h-48 flex items-end justify-between gap-2">
                {campaignData.dailyProgress.map((day, i) => (
                  <div key={i} className="flex-1 flex flex-col items-center gap-2">
                    <div className="w-full relative">
                      <div
                        className="w-full bg-gradient-to-t from-neon-green to-neon-green/50 rounded-t transition-all duration-500"
                        style={{ height: `${(day.recovered / maxDaily) * 140}px` }}
                      />
                      <div className="absolute -top-5 left-1/2 -translate-x-1/2 text-xs text-muted-foreground whitespace-nowrap">
                        ${(day.recovered / 1000).toFixed(0)}K
                      </div>
                    </div>
                    <span className="text-xs text-muted-foreground">{day.date.split(" ")[1]}</span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Debtor Status */}
          <Card className="bg-card border-border">
            <CardHeader>
              <CardTitle className="text-foreground flex items-center gap-2">
                <Users className="w-5 h-5 text-neon-blue" />
                Debtor Status Breakdown
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-foreground flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-neon-green" />
                      Resolved
                    </span>
                    <span className="text-muted-foreground">{campaignData.debtors.resolved} ({Math.round(campaignData.debtors.resolved / campaignData.debtors.total * 100)}%)</span>
                  </div>
                  <div className="h-3 bg-muted rounded-full overflow-hidden">
                    <div className="h-full bg-neon-green rounded-full" style={{ width: `${campaignData.debtors.resolved / campaignData.debtors.total * 100}%` }} />
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-foreground flex items-center gap-2">
                      <Clock className="w-4 h-4 text-amber-400" />
                      Pending
                    </span>
                    <span className="text-muted-foreground">{campaignData.debtors.pending} ({Math.round(campaignData.debtors.pending / campaignData.debtors.total * 100)}%)</span>
                  </div>
                  <div className="h-3 bg-muted rounded-full overflow-hidden">
                    <div className="h-full bg-amber-400 rounded-full" style={{ width: `${campaignData.debtors.pending / campaignData.debtors.total * 100}%` }} />
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-foreground flex items-center gap-2">
                      <XCircle className="w-4 h-4 text-red-400" />
                      Unreachable
                    </span>
                    <span className="text-muted-foreground">{campaignData.debtors.unreachable} ({Math.round(campaignData.debtors.unreachable / campaignData.debtors.total * 100)}%)</span>
                  </div>
                  <div className="h-3 bg-muted rounded-full overflow-hidden">
                    <div className="h-full bg-red-400 rounded-full" style={{ width: `${campaignData.debtors.unreachable / campaignData.debtors.total * 100}%` }} />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Agent Performance */}
        <Card className="bg-card border-border">
          <CardHeader>
            <CardTitle className="text-foreground flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-purple-400" />
              Agent Performance
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border">
                    <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Agent</th>
                    <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground">Calls</th>
                    <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground">Success Rate</th>
                    <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground">Recovered</th>
                    <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground">Performance</th>
                  </tr>
                </thead>
                <tbody>
                  {campaignData.agents.map((agent) => (
                    <tr key={agent.id} className="border-b border-border/50 hover:bg-muted/50">
                      <td className="py-3 px-4">
                        <div className="flex items-center gap-2">
                          <div className="w-8 h-8 rounded-lg bg-neon-green/10 flex items-center justify-center">
                            <span className="text-xs font-mono text-neon-green">{agent.name.slice(0, 2)}</span>
                          </div>
                          <span className="font-medium text-foreground">{agent.name}</span>
                        </div>
                      </td>
                      <td className="text-right py-3 px-4 text-foreground">{agent.calls.toLocaleString()}</td>
                      <td className="text-right py-3 px-4">
                        <span className={cn(
                          "font-medium",
                          agent.successRate >= 70 ? "text-neon-green" : agent.successRate >= 60 ? "text-amber-400" : "text-red-400"
                        )}>
                          {agent.successRate}%
                        </span>
                      </td>
                      <td className="text-right py-3 px-4 text-foreground font-medium">
                        ${(agent.recovered / 1000).toFixed(0)}K
                      </td>
                      <td className="text-right py-3 px-4">
                        <div className="w-24 h-2 bg-muted rounded-full overflow-hidden ml-auto">
                          <div 
                            className="h-full bg-neon-green rounded-full" 
                            style={{ width: `${agent.successRate}%` }} 
                          />
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>

        {/* Payment Methods */}
        <Card className="bg-card border-border">
          <CardHeader>
            <CardTitle className="text-foreground flex items-center gap-2">
              <DollarSign className="w-5 h-5 text-neon-green" />
              Payment Methods Distribution
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-3 gap-4">
              {campaignData.paymentMethods.map((pm, i) => (
                <div key={i} className="p-4 rounded-lg bg-muted/50">
                  <p className="text-sm text-muted-foreground">{pm.method}</p>
                  <p className="text-2xl font-display font-bold text-foreground mt-1">
                    ${(pm.amount / 1000).toFixed(0)}K
                  </p>
                  <p className="text-sm text-muted-foreground mt-1">{pm.count} payments</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </PageTransition>
  );
}
